apiVersion: v1
kind: Pod
metadata:
  name: aci-connector
  namespace: default
spec:
  containers:
  - name: aci-connector
    image: microsoft/aci-connector-k8s:latest
    imagePullPolicy: Always
    env:
      - name: AZURE_CLIENT_ID
        value: c33bd2b4-e71f-432e-b63e-2f1a31a639e9
      - name: AZURE_CLIENT_KEY
        value: b6e28372-31d4-4ea5-9b54-271f825e03aa
      - name: AZURE_TENANT_ID
        value: 72f988bf-86f1-41af-91ab-2d7cd011db47
      - name: AZURE_SUBSCRIPTION_ID
        value: 471d33fd-a776-405b-947c-467c291dc741
      - name: ACI_RESOURCE_GROUP
        value: aci-test