kind: Service
apiVersion: v1
metadata:
  name: go-web
  labels:
    app: go-web
spec:
  selector:
    run: go-web
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: go-web
        app: go-web
    spec:
      containers:
      - name: go-web
        image: kumazhang/go-web
        env:
        - name: HOST_PLATFORM
          value: "ACS Kubernetes"
        - name: BACK_COLOR
          value: "green"
        ports:
          - containerPort: 8080
